spring.application.name=controlefinancas
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=pass
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
security.jwt.secret-key=70941a6acbb8738b0ef58727ccbc87e24b41c2a5e4c0b9fd2e8eac4ec6e65a2a
security.jwt.issuer=pougos
spring.main.allow-circular-references=true
#verificar esse circular references
